---
- name: Setup webserver RHEL
  ansible.builtin.include_tasks: rhel_apache_collections.yml
  when: ansible_os_family == "RedHat"
  tags:
    - updaterhel

- name: Setup webserver Windows
  ansible.builtin.include_tasks: windows_iis_collections.yml
  when: ansible_os_family == "Windows"
  tags:
    - updatewin
